# Chess Play - Development Docker Compose Configuration
# 
# This setup is optimized for local development with hot reload
# Services: Express Backend, WebSocket Server, Frontend, MongoDB
#
# Usage:
#   docker-compose -f dockerdev-compose.yml up --build
#   docker-compose -f dockerdev-compose.yml down
#

services:
  # MongoDB Database
  mongo:
    image: mongo:7.0
    container_name: chess_play_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin_password
      MONGO_INITDB_DATABASE: chess_play
    volumes:
      # Named volume for persistent data
      - mongo_data:/data/db
    networks:
      - chess_network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  # Express Backend API Server (Port 3030)
  backend:
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    container_name: chess_play_backend
    restart: unless-stopped
    ports:
      - "3030:3030"
    environment:
      NODE_ENV: development
      PORT: 3030
      DB_URL: mongodb://admin:admin_password@mongo:27017/chess_play
    depends_on:
      mongo:
        condition: service_healthy
    volumes:
      # Hot reload: mount source code for live updates
      - ./express/src:/app/express/src
      # Exclude node_modules from bind mount
      - /app/express/node_modules
      - /app/node_modules
    networks:
      - chess_network
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3030', (r) => {if (r.statusCode !== 404) throw new Error(r.statusCode)})"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

  # WebSocket Server (Port 8080)
  ws-server:
    build:
      context: .
      dockerfile: ./docker/ws/Dockerfile
    container_name: chess_play_ws_server
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: development
      PORT: 8080
      DB_URL: mongodb://admin:admin_password@mongo:27017/chess_play
    depends_on:
      mongo:
        condition: service_healthy
    volumes:
      # Hot reload: mount source code for live updates
      - ./ws-server/src:/app/ws-server/src
      # Exclude node_modules from bind mount
      - /app/ws-server/node_modules
      - /app/node_modules
    networks:
      - chess_network
    healthcheck:
      test: ["CMD", "node", "-e", "require('net').createConnection({port:8080})"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

  # Frontend Next.js Dev Server (Port 3000)
  frontend:
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
    container_name: chess_play_frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_API_URL: http://localhost:3030
      NEXT_PUBLIC_WS_URL: ws://localhost:8080
    depends_on:
      - backend
      - ws-server
    volumes:
      # Hot reload: mount entire app directory for Next.js dev server
      - ./frontend/app:/app/frontend/app
      - ./frontend/components:/app/frontend/components
      - ./frontend/hooks:/app/frontend/hooks
      - ./frontend/public:/app/frontend/public
      - ./frontend/next.config.ts:/app/frontend/next.config.ts
      - ./frontend/tsconfig.json:/app/frontend/tsconfig.json
      # Exclude node_modules from bind mount
      - /app/frontend/node_modules
      - /app/node_modules
    networks:
      - chess_network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

volumes:
  # Persistent MongoDB data
  mongo_data:
    driver: local

networks:
  # Custom bridge network for service communication
  chess_network:
    driver: bridge
