FROM node:20-alpine

RUN npm install -g pnpm

WORKDIR /user/src/app

COPY ./database ./database
COPY package.json package.json
COPY pnpm-workspace.yaml pnpm-workspace.yaml
COPY ./express ./express

RUN pnpm install 

RUN cd express  && pnpm run build

EXPOSE 3030

CMD [ "pnpm","run","dev" ]