FROM node:20-alpine

RUN npm install -g pnpm

WORKDIR /user/src/app
ARG DATABASE_URL
COPY ./database ./database
COPY package.json package.json
COPY pnpm-workspace.yaml pnpm-workspace.yaml
COPY ./frontend ./frontend

RUN pnpm install 

RUN cd frontend && pnpm run build

EXPOSE 3000

CMD [ "pnpm","run","dev" ]